title: Tezana White
logo: IMG_8333.jpg
#description: I’m a cybersecurity enthusiast focused on exploring and securing digital ecosystems. Through hands-on projects and labs,
I investigate vulnerabilities, develop defense strategies, and share findings that help strengthen online security.e
show_downloads: true
theme: jekyll-theme-minimal
