title: Tezana White
logo: IMG_8333.jpg

description: I'm a cybersecurity enthusiast exploring digital ecosystems. I uncover vulnerabilities, develop defense strategies, and share insights to boost online security.
show_downloads: true
theme: jekyll-theme-minimal
